# Generated by Django 5.0.6 on 2024-06-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimg',
            name='Detect_Img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='upimg',
            name='hasil',
            field=models.TextField(default='(no detections)'),
        ),
        migrations.AddField(
            model_name='upimg',
            name='tanggal_detect',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='upimg',
            name='name',
            field=models.CharField(default='Anonim', max_length=50),
        ),
    ]
